[book]
authors = ["Funcky Contributors"]
language = "en"
multilingual = false
src = "src"
title = "Funcky User Guide"

[output.html]
site-url = "/funcky/"
additional-css = ["custom.css"]
git-repository-url = "https://github.com/polyadic/funcky"
git-repository-icon = "fa-github"
