name: Build and Deploy Website

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    # The website displays the latest version and needs
    # to be rebuilt when a new version is published.
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        name: Install Current .NET SDK
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.2'
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: yarn install
        working-directory: ./Documentation
      - name: Build Marble Graphics
        run: yarn build-marble-graphics
        working-directory: ./Documentation
      - name: Build Website and Documentation
        run: dotnet fsi Website/build.fsx
      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v1

  deploy_pages:
    needs: build
    if: github.ref_type == 'tag' || github.ref_name == 'main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
