name: Build Documentation

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.2'
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: yarn install
      - name: Build Marble Graphics
        run: yarn build-marble-graphics
        working-directory: ./Documentation
      - name: Build Documentation
        run: mdbook build
        working-directory: ./Documentation
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: success() && github.ref == 'refs/heads/main'
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./Documentation/book
          commit_message: ${{github.event.head_commit.message}}
